//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.06 at 12:57:31 AM CET 
//


package peerFile.wsdl;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the peerFile.wsdl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: peerFile.wsdl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EntityClasses }
     * 
     */
    public EntityClasses createEntityClasses() {
        return new EntityClasses();
    }

    /**
     * Create an instance of {@link AttributesToSet }
     * 
     */
    public AttributesToSet createAttributesToSet() {
        return new AttributesToSet();
    }

    /**
     * Create an instance of {@link AttributeToSet }
     * 
     */
    public AttributeToSet createAttributeToSet() {
        return new AttributeToSet();
    }

    /**
     * Create an instance of {@link EntityClass }
     * 
     */
    public EntityClass createEntityClass() {
        return new EntityClass();
    }

    /**
     * Create an instance of {@link LockedEntity }
     * 
     */
    public LockedEntity createLockedEntity() {
        return new LockedEntity();
    }

    /**
     * Create an instance of {@link Version }
     * 
     */
    public Version createVersion() {
        return new Version();
    }

    /**
     * Create an instance of {@link SystemConfigurations }
     * 
     */
    public SystemConfigurations createSystemConfigurations() {
        return new SystemConfigurations();
    }

    /**
     * Create an instance of {@link SystemConfiguration }
     * 
     */
    public SystemConfiguration createSystemConfiguration() {
        return new SystemConfiguration();
    }

    /**
     * Create an instance of {@link Entities }
     * 
     */
    public Entities createEntities() {
        return new Entities();
    }

    /**
     * Create an instance of {@link Versions }
     * 
     */
    public Versions createVersions() {
        return new Versions();
    }

    /**
     * Create an instance of {@link CreateAttributeTemplate }
     * 
     */
    public CreateAttributeTemplate createCreateAttributeTemplate() {
        return new CreateAttributeTemplate();
    }

    /**
     * Create an instance of {@link UserConfigurations }
     * 
     */
    public UserConfigurations createUserConfigurations() {
        return new UserConfigurations();
    }

    /**
     * Create an instance of {@link Attributes }
     * 
     */
    public Attributes createAttributes() {
        return new Attributes();
    }

    /**
     * Create an instance of {@link Attribute }
     * 
     */
    public Attribute createAttribute() {
        return new Attribute();
    }

    /**
     * Create an instance of {@link CreateAttributes }
     * 
     */
    public CreateAttributes createCreateAttributes() {
        return new CreateAttributes();
    }

    /**
     * Create an instance of {@link UserConfiguration }
     * 
     */
    public UserConfiguration createUserConfiguration() {
        return new UserConfiguration();
    }

    /**
     * Create an instance of {@link LockedEntities }
     * 
     */
    public LockedEntities createLockedEntities() {
        return new LockedEntities();
    }

    /**
     * Create an instance of {@link Entity }
     * 
     */
    public Entity createEntity() {
        return new Entity();
    }

    /**
     * Create an instance of {@link CreateAttributeTemplates }
     * 
     */
    public CreateAttributeTemplates createCreateAttributeTemplates() {
        return new CreateAttributeTemplates();
    }

    /**
     * Create an instance of {@link CreateAttribute }
     * 
     */
    public CreateAttribute createCreateAttribute() {
        return new CreateAttribute();
    }

}
